//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestUI.FingerPrinting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestUI.FingerPrinting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string cannot be null or empty!.
        /// </summary>
        internal static string ConnectionStringEmpty {
            get {
                return ResourceManager.GetString("ConnectionStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find SoundFingerprintingLib assembly!.
        /// </summary>
        internal static string CouldNotFindSoundLibError {
            get {
                return ResourceManager.GetString("CouldNotFindSoundLibError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End!.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensembling ended!.
        /// </summary>
        internal static string EnsemblingEnded {
            get {
                return ResourceManager.GetString("EnsemblingEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to file to be analyzed!.
        /// </summary>
        internal static string ErrorNoFileToAnalyze {
            get {
                return ResourceManager.GetString("ErrorNoFileToAnalyze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception in DAL!.
        /// </summary>
        internal static string ExceptioInDal {
            get {
                return ResourceManager.GetString("ExceptioInDal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.xml)|*.xml.
        /// </summary>
        internal static string ExportFilter {
            get {
                return ResourceManager.GetString("ExportFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File converted!.
        /// </summary>
        internal static string FileConverted {
            get {
                return ResourceManager.GetString("FileConverted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.csv)|*.csv.
        /// </summary>
        internal static string FileFilterCSV {
            get {
                return ResourceManager.GetString("FileFilterCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensemble (*.ens)|*.ens.
        /// </summary>
        internal static string FileFilterEnsemble {
            get {
                return ResourceManager.GetString("FileFilterEnsemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG File Interchange Format (*.jpg)|*.jpg.
        /// </summary>
        internal static string FileFilterJPeg {
            get {
                return ResourceManager.GetString("FileFilterJPeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.mp3)|*.mp3.
        /// </summary>
        internal static string FileFilterMp3 {
            get {
                return ResourceManager.GetString("FileFilterMp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.wav)|*.wav.
        /// </summary>
        internal static string FileFilterWav {
            get {
                return ResourceManager.GetString("FileFilterWav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list is empty. No files to be inserted to the database!.
        /// </summary>
        internal static string FileListEmpty {
            get {
                return ResourceManager.GetString("FileListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file list!.
        /// </summary>
        internal static string FileListEmptyCaption {
            get {
                return ResourceManager.GetString("FileListEmptyCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing in this folder is prohibited! Please select another path!.
        /// </summary>
        internal static string FileWriteDenial {
            get {
                return ResourceManager.GetString("FileWriteDenial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash Bins inserted!.
        /// </summary>
        internal static string HashBinsInserted {
            get {
                return ResourceManager.GetString("HashBinsInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image decomposed successfully!.
        /// </summary>
        internal static string ImageDecomposedSuccessfuly {
            get {
                return ResourceManager.GetString("ImageDecomposedSuccessfuly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image was drawn!.
        /// </summary>
        internal static string ImageIsDrawn {
            get {
                return ResourceManager.GetString("ImageIsDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insertion ended!.
        /// </summary>
        internal static string InsertionEnded {
            get {
                return ResourceManager.GetString("InsertionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string LineFeed {
            get {
                return ResourceManager.GetString("LineFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (*.mp3)|*.mp3|(*.wav)|*.wav|(*.flac)|*.flac.
        /// </summary>
        internal static string MusicFilter {
            get {
                return ResourceManager.GetString("MusicFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ntwrk.
        /// </summary>
        internal static string NetworkExtension {
            get {
                return ResourceManager.GetString("NetworkExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No such file!.
        /// </summary>
        internal static string NoSuchFile {
            get {
                return ResourceManager.GetString("NoSuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permutations.
        /// </summary>
        internal static string Permutations {
            get {
                return ResourceManager.GetString("Permutations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permutations generation successfully ended!.
        /// </summary>
        internal static string PermutationsGenerated {
            get {
                return ResourceManager.GetString("PermutationsGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition ended!.
        /// </summary>
        internal static string RecognitionEnded {
            get {
                return ResourceManager.GetString("RecognitionEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognition ended with an error!.
        /// </summary>
        internal static string RecognitionEndedWithAnError {
            get {
                return ResourceManager.GetString("RecognitionEndedWithAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to file to be drawn!.
        /// </summary>
        internal static string SelectAPathToBeDrawn {
            get {
                return ResourceManager.GetString("SelectAPathToBeDrawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file!.
        /// </summary>
        internal static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a folder with songs to be queried!.
        /// </summary>
        internal static string SelectFolderWithSongs {
            get {
                return ResourceManager.GetString("SelectFolderWithSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to file to dump into!.
        /// </summary>
        internal static string SelectPathToDump {
            get {
                return ResourceManager.GetString("SelectPathToDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select path to serialized ensemble.
        /// </summary>
        internal static string SelectPathToSerializedEnsemble {
            get {
                return ResourceManager.GetString("SelectPathToSerializedEnsemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Connection String to Validation database!.
        /// </summary>
        internal static string SelectValidationDB {
            get {
                return ResourceManager.GetString("SelectValidationDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Sound {
            get {
                object obj = ResourceManager.GetObject("Sound", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the path to network ensemble!.
        /// </summary>
        internal static string SpecifyPathToNetworkEnsemble {
            get {
                return ResourceManager.GetString("SpecifyPathToNetworkEnsemble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text files (*.txt)|*.txt.
        /// </summary>
        internal static string TextFiles {
            get {
                return ResourceManager.GetString("TextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training finished!.
        /// </summary>
        internal static string TrainingFinished {
            get {
                return ResourceManager.GetString("TrainingFinished", resourceCulture);
            }
        }
    }
}
